### ISSUE TITLE
any reason why magit.pushremote instead of remote.pushdefault ?

### ISSUE THREAD

**Issue by fommil** [magit/magit-push-remote#6]
There is a git config for this already, is there any reason you didn't want to use it?

It would be terrific if the git defaults were used instead.

**Comment by tarsius** [comment]
Probably I just didn't realize it existed. Or maybe I didn't want to use it, because that would also affect git but not magit's default push commands.

Anyway this extension now respects that also.

**Comment by fommil** [comment]
magit actually ignores the `remote.pushdefault` when pushing. It always goes to `@{upstream}`
