### ISSUE TITLE
missing dependency magit-diff-abbrev-arg 

### ISSUE THREAD

**Issue by fommil** [magit/magit-push-remote#8]
I'm not sure this is available in base magit, is it?

**Comment by fommil** [comment]
I've added this to my .emacs as a workaround

``` elisp
(defun magit-diff-abbrev-arg ()
  (format "--abbrev=%d" 7))
```

I'm sure you'll have a better idea what the correct replacement is

**Comment by tarsius** [comment]
See #5.
